### ISSUE TITLE
app crashed after +/- 2 days

### ISSUE THREAD

**Issue by kasteleman** [athombv/com.greenwavesystems#12]
The app crashes after 2 days with the following error:

Stack trace:

TypeError: Cannot read property 'index' of undefined
at /node_modules/homey-zwavedriver/lib/ZwaveDriver.js:393:48
at Array.forEach (native)
at CommandClass.<anonymous> (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:389:27)
at emitThree (events.js:102:20)
at CommandClass.emit (events.js:175:7)
at /homey-app/wireless/zwave.js:26:25
at /homey-app/helpers/client.js:1:1013
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:982)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)

Exit code: 1

**Comment by RobinBol** [comment]
#11 might be related

**Comment by RobinBol** [comment]
Could you let me know if this still happens after the greenwave app update to 1.0.5?

**Comment by RobinBol** [comment]
Due to inactivity this issue will be closed, if it still remains please let me know.
